# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0002_auto_20170401_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image1',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image2',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image3',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image4',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
    ]
