# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0004_auto_20170401_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Outdoor', max_length=50),
        ),
    ]
