# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0006_auto_20170401_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[('One Star', 'One Star'), ('Two Star', 'Two Star'), ('Three Star', 'Three Star'), ('Four Star', 'Four Star'), ('Five Star', 'Five Star')], null=True)),
                ('number_rating', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('forplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstone.Plant')),
            ],
        ),
    ]
