# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0007_ratingplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingplant',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
