# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0008_auto_20170401_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Thick', 'Thick'), ('Thin', 'Thin'), ('0-2 feet', '0-2 feet'), ('2-4 feet', '2-4 feet'), ('4-6 feet', '4-6 feet'), ('6-8 feet', '6-8 feet'), ('8-10 feet', '8-10 feet')], max_length=100)),
                ('psize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstone.Plant')),
            ],
        ),
    ]
