# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0011_remove_plant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantprices',
            name='pplant',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='firstone.Plant'),
            preserve_default=False,
        ),
    ]
