# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0012_plantprices_pplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantprices',
            name='pplant',
        ),
        migrations.RemoveField(
            model_name='plantprices',
            name='pprice',
        ),
        migrations.AddField(
            model_name='plantsize',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlantPrices',
        ),
    ]
