# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0015_auto_20170402_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='planter',
        ),
    ]
