# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0017_auto_20170403_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
