# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0021_ratingplant_foruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingplant',
            name='reviewtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
