# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0024_auto_20170404_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstone.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstone.UserProfile')),
            ],
        ),
    ]
