# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0027_auto_20170404_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
