# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0029_order_orderplantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderplantid',
        ),
    ]
