# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0032_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='plids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
