# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0034_auto_20170404_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plantsizes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
