# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0037_auto_20170404_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='plantsizes',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='plnames',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
