# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0041_auto_20170404_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'confirmed'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=50, null=True),
        ),
    ]
