# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0042_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'confirmed'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('new', 'new')], max_length=50, null=True),
        ),
    ]
