# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0044_auto_20170405_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Ornamental', 'Ornamental'), ('Herbs', 'Herbs'), ('Shrubs', 'Shrubs'), ('Flowering and Seasonal', 'Flowering and Seasonal'), ('Trees', 'Tree'), ('Palm', 'Palm'), ('Fruits', 'Fruits'), ('Grass', 'Grass'), ('Bonsai', 'Bonsai'), ('Seedling', 'Seedling')], default='Shrubs', max_length=50),
        ),
    ]
